site_name: derive-py
site_description: Python client for the Derive v3 API
docs_dir: docs
site_url: https://derivexyz.github.io/derive-py/
repo_url: https://github.com/derivexyz/derive-py

nav:
  - Home: index.md
  - API Reference: reference/

validation:
  nav:
    omitted_files: info

theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.suggest
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      linenums: false
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      baselevel: 2
      toc_depth: 3
      permalink: true

plugins:
  - include-markdown
  - search:
      lang: en
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            members_order: source
            group_by_category: true
            show_category_heading: true
            show_if_no_docstring: false
            inherited_members: false
            merge_init_into_class: true
            show_signature_annotations: true
            separate_signature: true
            signature_crossrefs: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/derivexyz/derive-py
      name: GitHub
