"""Enums used in the derive_client module."""

from enum import Enum, IntEnum, StrEnum


class ConnectionState(StrEnum):
    """Whether the WebSocket session is usable.

    CONNECTED means usable: authenticated and every channel resubscribed, not
    merely a socket that is open.
    """

    CONNECTED = "connected"
    RECONNECTING = "reconnecting"
    DISCONNECTED = "disconnected"


class RiskUniverseID(IntEnum):
    """Risk universe ID."""

    FALLBACK = 0
    PRIME = 1
    HYPE = 2
    ALTCOIN = 3
    RWA = 4


class GasPriority(IntEnum):
    SLOW = 25
    MEDIUM = 50
    FAST = 75


class Environment(Enum):
    """Environment."""

    PROD = "prod"
    TEST = "test"


class VaultAction(IntEnum):
    """VaultAction enum for vault operations."""

    CREATE = 0
    DEPOSIT = 1
    WITHDRAW = 2
    CANCEL = 3
    MINT_SHARES = 4
    BURN_SHARES = 5


class ProtocolScope(StrEnum):
    """On-chain authority a session key holds."""

    ADMIN = "admin"
    WITHDRAW = "withdraw"
    TRADE_ALL = "trade:all"
    TRADE_ORDERBOOK_ALL = "trade:orderbook:all"
    TRADE_ORDERBOOK_SPOT = "trade:orderbook:spot"
    TRADE_ORDERBOOK_PERP = "trade:orderbook:perp"
    TRADE_ORDERBOOK_OPTION = "trade:orderbook:option"
    TRADE_RFQ_ALL = "trade:rfq:all"
    TRADE_RFQ_SPOT = "trade:rfq:spot"
    TRADE_RFQ_PERP = "trade:rfq:perp"
    TRADE_RFQ_OPTION = "trade:rfq:option"
    TRANSFER_ALL = "transfer:all"
    TRANSFER_EXISTING_SUBACCOUNT = "transfer:existing_subaccount"
    TRANSFER_NEW_SUBACCOUNT = "transfer:new_subaccount"
    TRANSFER_DIFFERENT_OWNER_SUBACCOUNT = "transfer:different_owner_subaccount"
    CREATE_SESSION_KEY = "create_session_key"
    LIQUIDATE = "liquidate"
    VAULT_ALL = "vault:all"
    VAULT_CURATOR_CREATE = "vault:curator_create"
    VAULT_CURATOR_MINT_AND_BURN = "vault:curator_mint_and_burn"
    VAULT_USER_DEPOSIT = "vault:user_deposit"
    VAULT_USER_WITHDRAW = "vault:user_withdraw"
    VAULT_USER_CANCEL = "vault:user_cancel"

    @property
    def code(self) -> int:
        return _PROTOCOL_SCOPE_CODES[self]


_PROTOCOL_SCOPE_CODES: dict[ProtocolScope, int] = {
    ProtocolScope.ADMIN: 0,
    ProtocolScope.WITHDRAW: 1,
    ProtocolScope.TRADE_ALL: 2,
    ProtocolScope.TRADE_ORDERBOOK_ALL: 3,
    ProtocolScope.TRADE_ORDERBOOK_SPOT: 4,
    ProtocolScope.TRADE_ORDERBOOK_PERP: 5,
    ProtocolScope.TRADE_ORDERBOOK_OPTION: 6,
    ProtocolScope.TRADE_RFQ_ALL: 7,
    ProtocolScope.TRADE_RFQ_SPOT: 8,
    ProtocolScope.TRADE_RFQ_PERP: 9,
    ProtocolScope.TRADE_RFQ_OPTION: 10,
    ProtocolScope.TRANSFER_ALL: 11,
    ProtocolScope.TRANSFER_EXISTING_SUBACCOUNT: 12,
    ProtocolScope.TRANSFER_NEW_SUBACCOUNT: 13,
    ProtocolScope.TRANSFER_DIFFERENT_OWNER_SUBACCOUNT: 14,
    ProtocolScope.CREATE_SESSION_KEY: 15,
    ProtocolScope.LIQUIDATE: 16,
    ProtocolScope.VAULT_ALL: 17,
    ProtocolScope.VAULT_CURATOR_CREATE: 18,
    ProtocolScope.VAULT_CURATOR_MINT_AND_BURN: 19,
    ProtocolScope.VAULT_USER_DEPOSIT: 20,
    ProtocolScope.VAULT_USER_WITHDRAW: 21,
    ProtocolScope.VAULT_USER_CANCEL: 22,
}


class OffchainScope(StrEnum):
    """Server-side-only capability."""

    ACCOUNT_INFO = "account_info"
    DELETE_SESSION_KEY = "delete_session_key"


class EthereumJSONRPCErrorCode(IntEnum):
    # https://ethereum-json-rpc.com/errors
    PARSE_ERROR = -32700
    INVALID_REQUEST = -32600
    METHOD_NOT_FOUND = -32601
    INVALID_PARAMS = -32602
    INTERNAL_ERROR = -32603

    INVALID_INPUT = -32000
    RESOURCE_NOT_FOUND = -32001
    RESOURCE_UNAVAILABLE = -32002
    TRANSACTION_REJECTED = -32003
    METHOD_NOT_SUPPORTED = -32004
    LIMIT_EXCEEDED = -32005
    JSONRPC_VERSION_NOT_SUPPORTED = -32006


class DeriveJSONRPCErrorCode(IntEnum):
    # https://docs.derive.xyz/reference/error-codes
    NO_ERROR = 0
    RATE_LIMIT_EXCEEDED = -32000
    CONCURRENT_WS_CLIENTS_LIMIT_EXCEEDED = -32100
    PARSE_ERROR = -32700
    INVALID_REQUEST = -32600
    METHOD_NOT_FOUND = -32601
    INVALID_PARAMS = -32602
    INTERNAL_ERROR = -32603

    ORDER_CONFIRMATION_TIMEOUT = 9000
    ENGINE_CONFIRMATION_TIMEOUT = 9001

    MANAGER_NOT_FOUND = 10000
    ASSET_NOT_ERC20 = 10001
    WALLET_MISMATCH = 10002
    SUBACCOUNT_MISMATCH = 10003
    MULTIPLE_CURRENCIES_NOT_SUPPORTED = 10004
    MAX_SUBACCOUNTS_REACHED = 10005
    MAX_SESSION_KEYS_REACHED = 10006
    MAX_ASSETS_PER_SUBACCOUNT = 10007
    MAX_EXPIRIES_PER_SUBACCOUNT = 10008
    INVALID_RECIPIENT_SUBACCOUNT_ID = 10009
    PMRM_USDC_ONLY_COLLATERAL = 10010
    ERC20_INSUFFICIENT_ALLOWANCE = 10011
    ERC20_INSUFFICIENT_BALANCE = 10012
    PENDING_DEPOSIT = 10013
    PENDING_WITHDRAWAL = 10014
    PM2_COLLATERAL_CONSTRAINT = 10015

    INSUFFICIENT_FUNDS_ORDER = 11000
    ORDER_REJECTED_FROM_QUEUE = 11002
    ALREADY_CANCELLED = 11003
    ALREADY_FILLED = 11004
    ALREADY_EXPIRED = 11005
    ORDER_NOT_EXIST = 11006
    SELF_CROSS_DISALLOWED = 11007
    POST_ONLY_REJECT = 11008
    ZERO_LIQUIDITY = 11009
    POST_ONLY_INVALID_TYPE = 11010
    INVALID_SIGNATURE_EXPIRY = 11011
    INVALID_AMOUNT = 11012
    INVALID_LIMIT_PRICE = 11013
    FOK_NOT_FILLED = 11014
    MMP_FROZEN = 11015
    ALREADY_CONSUMED = 11016
    NON_UNIQUE_NONCE = 11017
    INVALID_NONCE_DATE = 11018
    OPEN_ORDERS_LIMIT_EXCEEDED = 11019
    NEGATIVE_ERC20_BALANCE = 11020
    INSTRUMENT_NOT_LIVE = 11021
    TRIGGER_ORDER_CANCELLED = 11050
    INVALID_TRIGGER_PRICE = 11051
    TRIGGER_ORDER_LIMIT_EXCEEDED = 11052
    TRIGGER_PRICE_TYPE_UNSUPPORTED = 11053
    TRIGGER_ORDER_REPLACE_UNSUPPORTED = 11054
    MARKET_ORDER_INVALID_TRIGGER_PRICE = 11055
    LEG_INSTRUMENTS_NOT_UNIQUE = 11100
    RFQ_NOT_FOUND = 11101
    QUOTE_NOT_FOUND = 11102
    RFQ_LEG_MISMATCH = 11103
    RFQ_NOT_OPEN = 11104
    RFQ_ID_MISMATCH = 11105
    INVALID_RFQ_COUNTERPARTY = 11106
    QUOTE_COST_TOO_HIGH = 11107
    AUCTION_NOT_ONGOING = 11200
    OPEN_ORDERS_NOT_ALLOWED = 11201
    PRICE_LIMIT_EXCEEDED = 11202
    LAST_TRADE_ID_MISMATCH = 11203
    MAKER_PROGRAM_NOT_FOUND = 19000
    ASSET_NOT_FOUND = 12000
    INSTRUMENT_NOT_FOUND = 12001
    CURRENCY_NOT_FOUND = 12002
    USDC_NO_CAPS = 12003
    INVALID_CHANNELS = 13000
    ACCOUNT_NOT_FOUND = 14000
    SUBACCOUNT_NOT_FOUND = 14001
    SUBACCOUNT_WITHDRAWN = 14002
    SESSIONKEY_EXPIRY_TOO_LOW = 14009
    SESSIONKEY_ALREADY_REGISTERED = 14010
    SESSIONKEY_REGISTERED_OTHER_ACCOUNT = 14011
    ADDRESS_NOT_CHECKSUMMED = 14012
    INVALID_ETH_ADDRESS = 14013
    INVALID_SIGNATURE = 14014
    NONCE_MISMATCH = 14015
    RAWTX_FUNCTION_MISMATCH = 14016
    RAWTX_CONTRACT_MISMATCH = 14017
    RAWTX_PARAMS_MISMATCH = 14018
    RAWTX_PARAM_VALUES_MISMATCH = 14019
    HEADER_WALLET_MISMATCH = 14020
    HEADER_WALLET_MISSING = 14021
    PRIVATE_CHANNEL_SUBSCRIPTION_FAILED = 14022
    SIGNER_NOT_OWNER = 14023
    CHAINID_MISMATCH = 14024
    MISSING_PRIVATE_PARAM = 14025
    SESSIONKEY_NOT_FOUND = 14026
    UNAUTHORIZED_RQF_MAKER = 14027
    CROSS_CURRENCY_RFQ_NOT_SUPPORTED = 14028
    SESSIONKEY_IP_NOT_WHITELISTED = 14029
    SESSIONKEY_EXPIRED = 14030
    UNAUTHORIZED_KEY_SCOPE = 14031
    SCOPE_NOT_ADMIN = 14032
    ACCOUNT_NOT_WHITELISTED_ATOMIC_ORDERS = 14033
    REFERRAL_CODE_NOT_FOUND = 14034
    RESTRICTED_REGION = 16000
    ACCOUNT_DISABLED_COMPLIANCE = 16001
    SENTINEL_AUTH_INVALID = 16100
    INVALID_BLOCK_NUMBER = 18000
    BLOCK_ESTIMATION_FAILED = 18001
    LIGHTACCOUNT_OWNER_MISMATCH = 18002
    VAULT_ERC20_ASSET_NOT_EXISTS = 18003
    VAULT_ERC20_POOL_NOT_EXISTS = 18004
    VAULT_ADD_ASSET_BEFORE_BALANCE = 18005
    INVALID_SWELL_SEASON = 18006
    VAULT_NOT_FOUND = 18007
    MAKER_PROGRAM_NOT_FOUND_19000 = 19000
