"""Tests for autogenerated API."""

import pytest

from derive_client.data_types.generated_models import (
    GetOrderHistoryRequest,
    GetSubaccountsRequest,
    PaginatedOrdersResult,
    PrivateGetSubaccountsResponse,
)


@pytest.mark.asyncio
async def test_get_private_get_subaccounts(client_admin_wallet):
    wallet = client_admin_wallet._auth.wallet
    params = GetSubaccountsRequest(wallet=wallet)
    result = await client_admin_wallet._private_api.rpc.get_subaccounts(params=params)
    assert isinstance(result, PrivateGetSubaccountsResponse)


@pytest.mark.asyncio
async def test_get_private_get_order_history(client_admin_wallet):
    subaccount_id = client_admin_wallet.active_subaccount.id
    params = GetOrderHistoryRequest(subaccount_id=subaccount_id)
    result = await client_admin_wallet._private_api.rpc.get_order_history(params=params)
    assert isinstance(result, PaginatedOrdersResult)
