"""
Single source of truth for file paths used across the codegen pipeline.
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
SPECS_DIR = REPO_ROOT / "specs"
DERIVE_CLIENT_DIR = REPO_ROOT / "derive_client"

# ---------------------------------------------------------------------------
# Source specs. Fetched via the curl commands documented in `make
# generate-models` itself (see Makefile). Names must match exactly.
# ---------------------------------------------------------------------------
OPENAPI_SPEC = SPECS_DIR / "openapi.json"
SUBSCRIPTIONS_ASYNCAPI = SPECS_DIR / "subscriptions.json"
WEBSOCKET_ASYNCAPI = SPECS_DIR / "websocket.json"

# ---------------------------------------------------------------------------
# Build intermediates — regenerated by the pipeline on every run, never
# hand-edited, gitignored. Listed here for the same reason as everything
# else: one definition, not one per script that touches them.
# ---------------------------------------------------------------------------
OPENAPI_SPEC_PATCHED = OPENAPI_SPEC.with_name(f"{OPENAPI_SPEC.stem}.patched{OPENAPI_SPEC.suffix}")
WEBSOCKET_CHANNELS = SPECS_DIR / "websocket-channels.json"

# ---------------------------------------------------------------------------
# Generated Python output
# ---------------------------------------------------------------------------
GENERATED_MODELS = DERIVE_CLIENT_DIR / "data_types" / "generated_models.py"
CHANNEL_MODELS = DERIVE_CLIENT_DIR / "data_types" / "channel_models.py"
WEBSOCKET_API = DERIVE_CLIENT_DIR / "_clients" / "websockets" / "api.py"
