name: Bump version
on:
  push:
    branches:
      - dev

# set permissions for the workflow
permissions:
  contents: write
  packages: write
  id-token: write


jobs:
  bump-version:
    runs-on: ubuntu-latest
    ## NOT on a specific commit
    # NOT IF THE LAST COMMIT IS A RELEASE COMMIT
    if: "!contains(github.event.head_commit.message, 'Bump version to v')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Configure git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: "2.1.3"
          virtualenvs-create: true
          virtualenvs-in-project: false
          virtualenvs-path: ~/my-custom-path
          installer-parallel: true
      - name: Bump Version
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          make dev-version

